sp3d/modules/transaksi/controllers/TaPemdaController.php
<?php

namespace frontend\modules\transaksi\controllers;

use Yii;
use frontend\models\transaksi\TaPemda;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaPemdaController implements the CRUD actions for TaPemda model.
 */
class TaPemdaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all TaPemda models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => TaPemda::find(),
        ]);

        return $this->renderAjax('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TaPemda model.
     * @param string $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new TaPemda model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TaPemda();

        if ($model->load(Yii::$app->request->post())){
            if($model->save()) echo 1; else echo 0;
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing TaPemda model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())){

            if($model->save()) echo 1; else echo 0;
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TaPemda model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if($this->findModel($id)->delete()) echo 1; else echo 0;
    }

    /**
     * Finds the TaPemda model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return TaPemda the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = TaPemda::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

sp3d/modules/transaksi/views/ta-pemda/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaPemda */
/* @var $form yii\widgets\ActiveForm */
/* @var $generator string helper base name TaPemda */
/* @var $generator string helper base name with camel to id Inflector ta-pemda */
/* @var $generator string helper base name with camel to word Inflector Ta Pemda */
?>

<div class="ta-pemda-form">
    <a href="javascript:void(0)" onclick="goLoad({url:'ta-pemda/index'})" class="btn btn-warning">List Ta Pemda</a>

    <?php $form = ActiveForm::begin(['id' => $model->formName(), 'options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'Tahun')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Kd_Prov')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Kd_Kab')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Nama_Pemda')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Nama_Provinsi')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Ibukota')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Alamat')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Nm_Bupati')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Jbt_Bupati')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Logo')->textInput() ?>

    <?= $form->field($model, 'C_Kode')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'C_Pemda')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'C_Data')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>
<?php $script = <<<JS
//regularly-ajax
$('form#{$model->formName()}').on('beforeSubmit', function(e){
    var \$form = $(this);
    $.post(
        \$form.attr('action'),
        \$form.serialize()
    ).done(function(res){
        if(res == 1){
            $(\$form).trigger('reset');
            goLoad({url : 'ta-pemda/index-npm?id={$data->xxx}'});
        } else {
            console.log('Fail but not error');
        }
    }).fail(function(){
        console.log('Server Error');
    });

    return false;
});

//if-use-upload-file
$('form#{$model->formName()}').on('beforeSubmit', function(e){
    var \$form = $(this);
    var \$data = new FormData($('form#Ta Pemda')[0]);

    $.ajax({
        url : \$form.attr('action'),
        data : \$data,
        type:'post',
        processData: false,
        contentType: false,
        success:function(res){
            if(res == 1){
                $(\$form).trigger('reset');
                //do next
                goLoad({url : 'ta-pemda/index'});
            } else {
                console.log('Fail but not error');
            }
        },
        error: function(jqXHR, textStatus, errorThrown){
            console.log('Fail but not error'+ textStatus); 
        }
    });

    return false;
});
JS;

$this->registerJs($script);

sp3d/modules/transaksi/views/ta-pemda/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaPemda */

$this->title = 'Create Ta Pemda';
$this->params['breadcrumbs'][] = ['label' => 'Ta Pemdas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ta-pemda-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

sp3d/modules/transaksi/views/ta-pemda/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ta Pemdas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ta-pemda-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <a href="javascript:void(0)" onclick="goLoad({url:'ta-pemda/create'})" class="btn btn-warning">Buat Ta Pemda</a>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'Tahun',
            'Kd_Prov',
            'Kd_Kab',
            'Nama_Pemda',
            'Nama_Provinsi',
            // 'Ibukota',
            // 'Alamat',
            // 'Nm_Bupati',
            // 'Jbt_Bupati',
            // 'Logo',
            // 'C_Kode',
            // 'C_Pemda',
            // 'C_Data',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
        </div>

sp3d/modules/transaksi/views/ta-pemda/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaPemda */

$this->title = 'Update Ta Pemda: ' . $model->Tahun;
$this->params['breadcrumbs'][] = ['label' => 'Ta Pemdas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->Tahun, 'url' => ['view', 'id' => $model->Tahun]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ta-pemda-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

sp3d/modules/transaksi/views/ta-pemda/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaPemda */

$this->title = $model->Tahun;
$this->params['breadcrumbs'][] = ['label' => 'Ta Pemdas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ta-pemda-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->Tahun], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->Tahun], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        Ajax
        <a href="javascript:void(0)" onclick="goLoad({url:'ta-pemda/update?id=<?= $model->id?>'})" class="btn btn-warning">Update Ta Pemda</a>
        <a href="javascript:void(0)" onclick="goSendLoad({msg:'Hapus ?', urlSend:'ta-pemda/delete?id=<?= $model->id?>', urlBack:'ta-pemda/index', typeSend:'post'})" class="btn btn-warning">Hapus Ta Pemda</a>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'Tahun',
            'Kd_Prov',
            'Kd_Kab',
            'Nama_Pemda',
            'Nama_Provinsi',
            'Ibukota',
            'Alamat',
            'Nm_Bupati',
            'Jbt_Bupati',
            'Logo',
            'C_Kode',
            'C_Pemda',
            'C_Data',
        ],
    ]) ?>

</div>