sp3d/modules/transaksi/controllers/TaDesaController.php
<?php
namespace sp3d\modules\transaksi\controllers;

use Yii;
use sp3d\models\transaksi\TaDesa;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaDesaController implements the CRUD actions for TaDesa model.
 */
class TaDesaController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionDesaIndex($id, $tahun, $effect)
    {
        $dataProvider = TaDesa::find()->where(['Kd_Desa' => $id,'Tahun' => $tahun]);

        return $this->renderAjax('desa-index', [
            'dataProvider' => $dataProvider,
            'id' => $id,
            'tahun' => $tahun,
            'effect' => $effect
        ]);
    }

    public function actionDesaCreate($id, $tahun)
    {
        $m = TaDesa::findOne(['Tahun' => $tahun, 'Kd_Desa' => $id]);
        if($m == null){
            $model = new TaDesa();

            if ($model->load(Yii::$app->request->post())){
                if($model->save()) echo 1; else echo 0;
            } else {
                return $this->renderAjax('desa-form', [
                    'model' => $model,
                    'id' => $id,
                    'tahun' => $tahun
                ]);
            }    
        } else {
            return $this->renderAjax('desa-view', [
                'model' => $m,
                'id' => $id,
                'tahun' => $tahun
            ]);
        }
        
    }

    public function actionDesaUpdate($id, $tahun)
    {
        $model = $this->findModel($tahun, $id);

        if ($model->load(Yii::$app->request->post())){
            if($model->save()) echo 1; else echo 0;
        } else {
            return $this->renderAjax('desa-form', [
                'model' => $model,
                'id' => $id,
                'tahun' => $tahun
            ]);
        }
    }

    public function actionDesaView($id, $tahun)
    {
        return $this->renderAjax('desa-view', [
            'model' => $this->findModel($tahun, $id),
            'id' => $id,
            'tahun' => $tahun
        ]);
    }

    public function actionDesaDelete($id, $tahun)
    {
        if($this->findModel($tahun,$id)->delete()) echo 1; else echo 0;
    }


    

    /**
     * Lists all TaDesa models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => TaDesa::find(),
        ]);

        return $this->renderAjax('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TaDesa model.
     * @param string $Tahun
     * @param string $Kd_Desa
     * @return mixed
     */
    public function actionView($Tahun, $Kd_Desa)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($Tahun, $Kd_Desa),
        ]);
    }

    /**
     * Creates a new TaDesa model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TaDesa();

        if ($model->load(Yii::$app->request->post())){
            if($model->save()) echo 1; else echo 0;
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing TaDesa model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $Tahun
     * @param string $Kd_Desa
     * @return mixed
     */
    public function actionUpdate($Tahun, $Kd_Desa)
    {
        $model = $this->findModel($Tahun, $Kd_Desa);

        if ($model->load(Yii::$app->request->post())){

            if($model->save()) echo 1; else echo 0;
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TaDesa model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $Tahun
     * @param string $Kd_Desa
     * @return mixed
     */
    public function actionDelete($Tahun, $Kd_Desa)
    {
        if($this->findModel($id)->delete()) echo 1; else echo 0;
    }

    /**
     * Finds the TaDesa model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $Tahun
     * @param string $Kd_Desa
     * @return TaDesa the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($Tahun, $Kd_Desa)
    {
        if (($model = TaDesa::findOne(['Tahun' => $Tahun, 'Kd_Desa' => $Kd_Desa])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

sp3d/modules/transaksi/views/ta-desa/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaDesa */
/* @var $form yii\widgets\ActiveForm */
/* @var $generator string helper base name TaDesa */
/* @var $generator string helper base name with camel to id Inflector ta-desa */
/* @var $generator string helper base name with camel to word Inflector Ta Desa */
?>

<div class="ta-desa-form">
    <a href="javascript:void(0)" onclick="goLoad({url:'ta-desa/index'})" class="btn btn-warning">List Ta Desa</a>

    <?php $form = ActiveForm::begin(['id' => $model->formName(), 'options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'Tahun')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Kd_Desa')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Nm_Kades')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Jbt_Kades')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Nm_Sekdes')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'NIP_Sekdes')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Jbt_Sekdes')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Nm_Kaur_Keu')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Jbt_Kaur_Keu')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Nm_Bendahara')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Jbt_Bendahara')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'No_Perdes')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Tgl_Perdes')->textInput() ?>

    <?= $form->field($model, 'No_Perdes_PB')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Tgl_Perdes_PB')->textInput() ?>

    <?= $form->field($model, 'No_Perdes_PJ')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Tgl_Perdes_PJ')->textInput() ?>

    <?= $form->field($model, 'Alamat')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Ibukota')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Status')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'NPWP')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>
<?php $script = <<<JS
//regularly-ajax
$('form#{$model->formName()}').on('beforeSubmit', function(e){
    var \$form = $(this);
    $.post(
        \$form.attr('action'),
        \$form.serialize()
    ).done(function(res){
        if(res == 1){
            $(\$form).trigger('reset');
            goLoad({url : 'ta-desa/index-npm?id={$data->xxx}'});
        } else {
            console.log('Fail but not error');
        }
    }).fail(function(){
        console.log('Server Error');
    });

    return false;
});

//if-use-upload-file
$('form#{$model->formName()}').on('beforeSubmit', function(e){
    var \$form = $(this);
    var \$data = new FormData($('form#Ta Desa')[0]);

    $.ajax({
        url : \$form.attr('action'),
        data : \$data,
        type:'post',
        processData: false,
        contentType: false,
        success:function(res){
            if(res == 1){
                $(\$form).trigger('reset');
                //do next
                goLoad({url : 'ta-desa/index'});
            } else {
                console.log('Fail but not error');
            }
        },
        error: function(jqXHR, textStatus, errorThrown){
            console.log('Fail but not error'+ textStatus); 
        }
    });

    return false;
});
JS;

$this->registerJs($script);

sp3d/modules/transaksi/views/ta-desa/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaDesa */

$this->title = 'Create Ta Desa';
$this->params['breadcrumbs'][] = ['label' => 'Ta Desas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ta-desa-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

sp3d/modules/transaksi/views/ta-desa/desa-form.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaBidang */
/* @var $form yii\widgets\ActiveForm */
/* @var $generator string helper base name TaBidang */
/* @var $generator string helper base name with camel to id Inflector ta-bidang */
/* @var $generator string helper base name with camel to word Inflector Ta Bidang */
if($model->isNewRecord){
    $model->Tahun = $tahun;
    $model->Nm_Kades = $model->Nm_Sekdes = $model->NIP_Sekdes = $model->Nm_Bendahara = $model->Nm_Kaur_Keu = '-';
    $model->Jbt_Kades = 'Kepala Desa';
    $model->Jbt_Sekdes = 'Sekretaris Desa';
    $model->Jbt_Bendahara = 'Bendahara Desa';
    $model->Jbt_Kaur_Keu = 'Kaur Keuangan Desa';
    $model->Kd_Desa = $id;
    $model->Status = 1;
    $idkec = substr($id, 0, 7);
    $model->kd_kecamatan = $idkec[0];
}
?>

<div class="ta-bidang-form animated slideInLeft">
    <?php if(!$model->isNewRecord){ ?>
    <a href="javascript:void(0)" onclick="goLoad({elm:'#penganggaran-datadesa', url:'/transaksi/ta-desa/desa-view?id=<?=$id?>&tahun=<?=$tahun?>&effect=lightSpeedIn'})" class="btn btn-warning">Kembali Ke Data Umum Desa</a>
    <?php } ?>

    <?php $form = ActiveForm::begin(['id' => $model->formName()]); ?>

    <?= $form->field($model, 'Tahun')->hiddenInput(['maxlength' => true])->label(false) ?>
    <?= $form->field($model, 'Kd_Desa')->hiddenInput(['maxlength' => true])->label(false) ?>
    <?= $form->field($model, 'kd_kecamatan')->hiddenInput(['maxlength' => true])->label(false) ?>
    <?= $form->field($model, 'Status')->hiddenInput(['maxlength' => true])->label(false) ?>
    <div class="row">
        <div class="col-md-4">
            <?= $form->field($model, 'Nm_Kades')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'Jbt_Kades')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'Nm_Sekdes')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'NIP_Sekdes')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'Jbt_Sekdes')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'Nm_Bendahara')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'Jbt_Bendahara')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'Nm_Kaur_Keu')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'Jbt_Kaur_Keu')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'No_Perdes')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'Tgl_Perdes')->textInput() ?>
            <?= $form->field($model, 'No_Perdes_PB')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'Tgl_Perdes_PB')->textInput() ?>
        </div>
        <div class="col-md-4">
            <?= $form->field($model, 'No_Perdes_PJ')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'Tgl_Perdes_PJ')->textInput() ?>
            <?= $form->field($model, 'Alamat')->textarea(['maxlength' => true]) ?>
            <?= $form->field($model, 'Ibukota')->textInput(['maxlength' => true]) ?>
            <?= $form->field($model, 'NPWP')->textInput(['maxlength' => true]) ?>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Isi' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
    <br>
    <br>
    <br>
</div>
<?php $script = <<<JS
$('#tadesa-tgl_perdes, #tadesa-tgl_perdes_pb, #tadesa-tgl_perdes_pj').datetimepicker({
    format:'Y-m-d',
    mask:true
});
//regularly-ajax
$('form#{$model->formName()}').on('beforeSubmit', function(e){
    var \$form = $(this);
    $.post(
        \$form.attr('action'),
        \$form.serialize()
    ).done(function(res){
        if(res == 1){
            $(\$form).trigger('reset');
            goLoad({elm:'#penganggaran-area',url : '/transaksi/ta-desa/desa-view?id={$id}&tahun={$tahun}&effect=lightSpeedIn'});
        } else {
            console.log('Fail but not error');
        }
    }).fail(function(){
        console.log('Server Error');
    });

    return false;
});
JS;

$this->registerJs($script);

sp3d/modules/transaksi/views/ta-desa/desa-index.php
<?php
use hscstudio\mimin\components\Mimin;
?>
<!-- Box Comment -->
<div class="box box-widget animated <?=($effect)?$effect:'slideInRight'?>">
<div class="box-header with-border">
  <div class="user-block">
    <img class="img-circle" src="css/adminlte/dist/img/user1-128x128.jpg" alt="User Image">
    <span class="username"><a href="#">Admin.</a></span>
    <span class="description">Tabel Perangkat</span>
  </div>
  <!-- /.user-block -->
  <div class="box-tools">
    <button type="button" class="btn btn-box-tool" data-toggle="tooltip" title="Mark as read">
      <i class="fa fa-circle-o"></i></button>
    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
    </button>
    <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
  </div>
  <!-- /.box-tools -->
</div>
<!-- /.box-header -->
<div class="box-body">
  	<!-- post text -->
  	<a href="javascript:void(0)" onclick="goLoad({elm:'#desa-container', url:'/transaksi/ta-perangkat/perangkat-index?id=<?=$id?>&tahun=<?=$tahun?>'})" class="btn btn-sm btn-warning">Kembali</a>
  	<?php if(Mimin::checkRoute('transaksi/ta-perangkat/desa-create')): ?>
	<a href="javascript:void(0)" onclick="goLoad({elm:'#desa-container', url:'/transaksi/ta-desa/desa-create?id=<?=$id?>&tahun=<?=$tahun?>'})" class="btn btn-sm btn-warning">Tambah Perangkat Desa</a><hr>
	<?php endif; ?>
  	
  	<table id="ta-perangkat-table" class="display table" width="100%">
	    <thead>
	        <tr>
	            <th>Kades</th>
	            <th>Sekdes</th>
	            <th>Bendahara</th>
	            <th>Alamat</th>
	            <th>Status</th>
	            <th>Action</th>
	        </tr>
	    </thead>
	    <tfoot>
	        <tr>
	            <th>Kades</th>
	            <th>Sekdes</th>
	            <th>Bendahara</th>
	            <th>Alamat</th>
	            <th>Status</th>
	            <th>Action</th>
	        </tr>
	    </tfoot>
	    <tbody>
	    	<?php foreach ($dataProvider->all() as $v): ?>
	        <tr>
	            <th><?= $v->Nm_Kades ?></th>
	            <th><?= $v->Nm_Sekdes ?></th>
	            <th><?= $v->Nm_Bendahara ?></th>
	            <th><?= $v->Alamat ?></th>
	            <th><?= $v->Status ?></th>
	            <th>
	            	<?php if(Mimin::checkRoute('transaksi/ta-desa/desa-delete')): ?>
	            	<a href="javascript:void(0)" onclick="goSendLoad({elmChange:'#desa-container',msg:'Hapus Data Perangkat Desa?', urlSend:'/transaksi/ta-desa/desa-delete?id=<?=$id?>&tahun=<?=$v->Tahun?>', urlBack:'/transaksi/ta-desa/desa-index?id=<?=$id?>&tahun=<?=$tahun?>&effect=rubberBand', typeSend:'get'})" class="label label-danger">Hapus</a>
	            	<?php endif; ?>

	            	<?php if(Mimin::checkRoute('transaksi/ta-desa/desa-view')): ?>
	            	<a href="javascript:void(0)" onclick="goLoad({elm:'#desa-container', url:'/transaksi/ta-desa/desa-view?id=<?=$id?>&tahun=<?=$v->Tahun?>'})" class="label label-warning">View</a>
	            	<?php endif; ?>
	            </th>
	        </tr>
	        <?php endforeach; ?>
	    </tbody>
	</table>
</div>
</div>
<!-- /.box -->
<?php
/*'Tahun',
            'Kd_Desa',
            'Nm_Kades',
            'Jbt_Kades',
            'Nm_Sekdes',*/
$scripts =<<<JS
	$('#ta-perangkat-table').DataTable();
JS;

$this->registerJs($scripts);

sp3d/modules/transaksi/views/ta-desa/desa-view.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaBidang */
?>
<div class="ta-perangkat-view animated slideInLeft">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>            
        <?php if(is_null($model->Tahun)){ ?>

            <?php if(Mimin::checkRoute('transaksi/ta-perangkat/desa-create')): ?>
            <a href="javascript:void(0)" onclick="goLoad({elm:'#vtab-data-umum-desa', url:'/transaksi/ta-desa/desa-create?id=<?=$id?>&tahun=<?=$tahun?>'})" class="btn btn-sm btn-warning">Tambah Data Umum Desa</a>
            <!-- <a href="javascript:void(0)" onclick="goLoad({elm:'#vtab-data-umum-desa', url:'/transaksi/ta-perangkat/desa-index?id=<?=$id?>&tahun=<?=$tahun?>&effect=lightSpeedIn'})" class="btn btn-warning">List Perangkat</a>
         <a href="javascript:void(0)" onclick="goSendLoad({elmChange:'#vtab-data-umum-desa',msg:'Hapus Perangkat Desa?', urlSend:'/transaksi/ta-perangkat/desa-delete?id=<?=$id?>&tahun=<?=$tahun?>&kd=<?=$model->Kd_Desa?>&no=<?=$model->Kd_Desa?>', urlBack:'/transaksi/ta-perangkat/desa-index?id=<?=$id?>&tahun=<?=$tahun?>&effect=lightSpeedIn', typeSend:'get'})" class="btn btn-warning">Hapus Perangkat</a> -->
            <?php endif; ?>
        <?php } else { ?>
            <a href="javascript:void(0)" onclick="goLoad({elm:'#penganggaran-area', url:'/transaksi/ta-desa/desa-update?id=<?=$id?>&tahun=<?=$tahun?>'})" class="btn btn-sm btn-warning">Update Data</a>
            <a href="<?= Url::to(['/data-umum/pdf?bagian=data-desa&kd_desa='.$model->Kd_Desa], true) ?>" target="_blank" class="btn btn-sm btn-info">PDF</a>
        <?php } ?>
    </p>

    <div class="row">
        <div class="col-md-6 col-lg-4">
            <b>Tahun :</b><br><?= $model->Tahun ?><br>
            <b>Kode Desa :</b><br><?= $model->Kd_Desa ?><br>
            <b>Nama :</b><br><?= $model->Nm_Kades ?><br>
            <b>Jabatan :</b><br><?= $model->Jbt_Kades ?><br>
        </div>
        <div class="col-md-6 col-lg-4">
            <b>Nama :</b><br><?= $model->Nm_Sekdes ?><br>
            <b>NIP :</b><br><?= $model->NIP_Sekdes ?><br>
            <b>Jabatan :</b><br><?= $model->Jbt_Sekdes ?><br>
            
            <b>Nama :</b><br><?= $model->Nm_Kaur_Keu ?><br>
            <b>Jabatan :</b><br><?= $model->Jbt_Kaur_Keu ?><br>

            <b>Nama :</b><br><?= $model->Nm_Bendahara ?><br>
            <b>Bendahara :</b><br><?= $model->Jbt_Bendahara ?><br>
        </div>
        <div class="col-md-6 col-lg-4">
            <b>No. Perdes :</b><br><?= $model->No_Perdes ?><br>
            <b>Tanggal Perdes :</b><br><?= $model->Tgl_Perdes ?><br>

            <!-- <b>Tahun :</b><br><?= $model->No_Perdes_PB ?><br>
            <b>Tahun :</b><br><?= $model->Tgl_Perdes_PB ?><br>
            <b>Tahun :</b><br><?= $model->No_Perdes_PJ ?><br>
            <b>Tahun :</b><br><?= $model->Tgl_Perdes_PJ ?><br> -->

            <b>Alamat :</b><br><?= $model->Alamat ?><br>
            <b>Ibukota :</b><br><?= $model->Ibukota ?><br>
            <b>NPWP :</b><br><?= $model->NPWP ?><br>
        </div>
    </div>    
</div>

sp3d/modules/transaksi/views/ta-desa/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ta Desas';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ta-desa-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <a href="javascript:void(0)" onclick="goLoad({url:'ta-desa/create'})" class="btn btn-warning">Buat Ta Desa</a>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'Tahun',
            'Kd_Desa',
            'Nm_Kades',
            'Jbt_Kades',
            'Nm_Sekdes',
            // 'NIP_Sekdes',
            // 'Jbt_Sekdes',
            // 'Nm_Kaur_Keu',
            // 'Jbt_Kaur_Keu',
            // 'Nm_Bendahara',
            // 'Jbt_Bendahara',
            // 'No_Perdes',
            // 'Tgl_Perdes',
            // 'No_Perdes_PB',
            // 'Tgl_Perdes_PB',
            // 'No_Perdes_PJ',
            // 'Tgl_Perdes_PJ',
            // 'Alamat',
            // 'Ibukota',
            // 'Status',
            // 'NPWP',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
        </div>

sp3d/modules/transaksi/views/ta-desa/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaDesa */

$this->title = 'Update Ta Desa: ' . $model->Tahun;
$this->params['breadcrumbs'][] = ['label' => 'Ta Desas', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->Tahun, 'url' => ['view', 'Tahun' => $model->Tahun, 'Kd_Desa' => $model->Kd_Desa]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ta-desa-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

sp3d/modules/transaksi/views/ta-desa/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaDesa */

$this->title = $model->Tahun;
$this->params['breadcrumbs'][] = ['label' => 'Ta Desas', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ta-desa-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'Tahun' => $model->Tahun, 'Kd_Desa' => $model->Kd_Desa], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'Tahun' => $model->Tahun, 'Kd_Desa' => $model->Kd_Desa], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        Ajax
        <a href="javascript:void(0)" onclick="goLoad({url:'ta-desa/update?id=<?= $model->id?>'})" class="btn btn-warning">Update Ta Desa</a>
        <a href="javascript:void(0)" onclick="goSendLoad({msg:'Hapus ?', urlSend:'ta-desa/delete?id=<?= $model->id?>', urlBack:'ta-desa/index', typeSend:'post'})" class="btn btn-warning">Hapus Ta Desa</a>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'Tahun',
            'Kd_Desa',
            'Nm_Kades',
            'Jbt_Kades',
            'Nm_Sekdes',
            'NIP_Sekdes',
            'Jbt_Sekdes',
            'Nm_Kaur_Keu',
            'Jbt_Kaur_Keu',
            'Nm_Bendahara',
            'Jbt_Bendahara',
            'No_Perdes',
            'Tgl_Perdes',
            'No_Perdes_PB',
            'Tgl_Perdes_PB',
            'No_Perdes_PJ',
            'Tgl_Perdes_PJ',
            'Alamat',
            'Ibukota',
            'Status',
            'NPWP',
        ],
    ]) ?>

</div>