sp3d/modules/transaksi/controllers/TaUserMenuController.php
<?php
namespace sp3d\modules\transaksi\controllers;

use Yii;
use sp3d\models\transaksi\TaUserMenu;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * TaUserMenuController implements the CRUD actions for TaUserMenu model.
 */
class TaUserMenuController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionDesaIndex($id, $tahun, $effect)
    {
        $dataProvider = TaKegiatan::find()->where(['Kd_Desa' => $id,'Tahun' => $tahun]);

        return $this->renderAjax('desa-index', [
            'dataProvider' => $dataProvider,
            'id' => $id,
            'tahun' => $tahun,
            'effect' => $effect
        ]);
    }

    public function actionDesaCreate($id, $tahun)
    {
        $model = new TaKegiatan();

        if ($model->load(Yii::$app->request->post())){
            if($model->save()) echo 1; else echo 0;
        } else {
            return $this->renderAjax('desa-form', [
                'model' => $model,
                'id' => $id,
                'tahun' => $tahun
            ]);
        }
    }

    public function actionDesaUpdate($id, $tahun, $kd)
    {
        $model = TaKegiatan::findOne(['Kd_Desa' => $id,'Tahun' => $tahun, 'Kd_Keg' => $kd]);

        if ($model->load(Yii::$app->request->post())){
            if($model->save()) echo 1; else echo 0;
        } else {
            return $this->renderAjax('desa-form', [
                'model' => $model,
                'id' => $id,
                'tahun' => $tahun
            ]);
        }
    }

    public function actionDesaView($id, $tahun, $kd)
    {
        $model = TaKegiatan::findOne(['Kd_Desa' => $id,'Tahun' => $tahun, 'Kd_Keg' => $kd]);

        return $this->renderAjax('desa-view', [
            'model' => $model,
            'id' => $id,
            'tahun' => $tahun
        ]);
    }

    public function actionDesaDelete($id, $tahun, $kd)
    {
        if(TaKegiatan::findOne(['Kd_Desa' => $id,'Tahun' => $tahun, 'Kd_Keg' => $kd])->delete()) echo 1; else echo 0;
    }


    



    /**
     * Lists all TaUserMenu models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => TaUserMenu::find(),
        ]);

        return $this->renderAjax('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single TaUserMenu model.
     * @param string $UserID
     * @param string $IDMenu
     * @return mixed
     */
    public function actionView($UserID, $IDMenu)
    {
        return $this->renderAjax('view', [
            'model' => $this->findModel($UserID, $IDMenu),
        ]);
    }

    /**
     * Creates a new TaUserMenu model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new TaUserMenu();

        if ($model->load(Yii::$app->request->post())){
            if($model->save()) echo 1; else echo 0;
        } else {
            return $this->renderAjax('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing TaUserMenu model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $UserID
     * @param string $IDMenu
     * @return mixed
     */
    public function actionUpdate($UserID, $IDMenu)
    {
        $model = $this->findModel($UserID, $IDMenu);

        if ($model->load(Yii::$app->request->post())){

            if($model->save()) echo 1; else echo 0;
        } else {
            return $this->renderAjax('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing TaUserMenu model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $UserID
     * @param string $IDMenu
     * @return mixed
     */
    public function actionDelete($UserID, $IDMenu)
    {
        if($this->findModel($id)->delete()) echo 1; else echo 0;
    }

    /**
     * Finds the TaUserMenu model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $UserID
     * @param string $IDMenu
     * @return TaUserMenu the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($UserID, $IDMenu)
    {
        if (($model = TaUserMenu::findOne(['UserID' => $UserID, 'IDMenu' => $IDMenu])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

sp3d/modules/transaksi/views/ta-user-menu/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaUserMenu */
/* @var $form yii\widgets\ActiveForm */
/* @var $generator string helper base name TaUserMenu */
/* @var $generator string helper base name with camel to id Inflector ta-user-menu */
/* @var $generator string helper base name with camel to word Inflector Ta User Menu */
?>

<div class="ta-user-menu-form">
    <a href="javascript:void(0)" onclick="goLoad({url:'ta-user-menu/index'})" class="btn btn-warning">List Ta User Menu</a>

    <?php $form = ActiveForm::begin(['id' => $model->formName(), 'options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'UserID')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'IDMenu')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Otoritas')->textInput(['maxlength' => true]) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>
<?php $script = <<<JS
//regularly-ajax
$('form#{$model->formName()}').on('beforeSubmit', function(e){
    var \$form = $(this);
    $.post(
        \$form.attr('action'),
        \$form.serialize()
    ).done(function(res){
        if(res == 1){
            $(\$form).trigger('reset');
            goLoad({url : 'ta-user-menu/index-npm?id={$data->xxx}'});
        } else {
            console.log('Fail but not error');
        }
    }).fail(function(){
        console.log('Server Error');
    });

    return false;
});

//if-use-upload-file
$('form#{$model->formName()}').on('beforeSubmit', function(e){
    var \$form = $(this);
    var \$data = new FormData($('form#Ta User Menu')[0]);

    $.ajax({
        url : \$form.attr('action'),
        data : \$data,
        type:'post',
        processData: false,
        contentType: false,
        success:function(res){
            if(res == 1){
                $(\$form).trigger('reset');
                //do next
                goLoad({url : 'ta-user-menu/index'});
            } else {
                console.log('Fail but not error');
            }
        },
        error: function(jqXHR, textStatus, errorThrown){
            console.log('Fail but not error'+ textStatus); 
        }
    });

    return false;
});
JS;

$this->registerJs($script);

sp3d/modules/transaksi/views/ta-user-menu/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaUserMenu */

$this->title = 'Create Ta User Menu';
$this->params['breadcrumbs'][] = ['label' => 'Ta User Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ta-user-menu-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

sp3d/modules/transaksi/views/ta-user-menu/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Ta User Menus';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ta-user-menu-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <a href="javascript:void(0)" onclick="goLoad({url:'ta-user-menu/create'})" class="btn btn-warning">Buat Ta User Menu</a>
    </p>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'UserID',
            'IDMenu',
            'Otoritas',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
        </div>

sp3d/modules/transaksi/views/ta-user-menu/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaUserMenu */

$this->title = 'Update Ta User Menu: ' . $model->UserID;
$this->params['breadcrumbs'][] = ['label' => 'Ta User Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->UserID, 'url' => ['view', 'UserID' => $model->UserID, 'IDMenu' => $model->IDMenu]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="ta-user-menu-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

sp3d/modules/transaksi/views/ta-user-menu/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\transaksi\TaUserMenu */

$this->title = $model->UserID;
$this->params['breadcrumbs'][] = ['label' => 'Ta User Menus', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="ta-user-menu-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'UserID' => $model->UserID, 'IDMenu' => $model->IDMenu], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'UserID' => $model->UserID, 'IDMenu' => $model->IDMenu], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        Ajax
        <a href="javascript:void(0)" onclick="goLoad({url:'ta-user-menu/update?id=<?= $model->id?>'})" class="btn btn-warning">Update Ta User Menu</a>
        <a href="javascript:void(0)" onclick="goSendLoad({msg:'Hapus ?', urlSend:'ta-user-menu/delete?id=<?= $model->id?>', urlBack:'ta-user-menu/index', typeSend:'post'})" class="btn btn-warning">Hapus Ta User Menu</a>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'UserID',
            'IDMenu',
            'Otoritas',
        ],
    ]) ?>

</div>